app/clients/models.py
from flask_sqlalchemy import SQLAlchemy
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash


# objeto de base de datos
#db = SQLAlchemy()

#relaciones entre tablas

# Modelos para el paquete clientes
# class Cliente(db.Model, UserMixin):
#     __tablename__ = 'clientes'
#     id = db.Column(db.Integer, primary_key=True)
#     name = db.Column(db.String(80), nullable=False)
#     email = db.Column(db.String(256), unique=True, nullable=False)
#     password = db.Column(db.String(128), nullable=False)
#     is_admin = db.Column(db.Boolean, default=False)

app/clients/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, PasswordField
from wtforms.validators import DataRequired, Email, Length

class LoginClientes(FlaskForm):
    password = PasswordField('Password', validators=[DataRequired()])
    email = StringField('Email', validators=[DataRequired(), Email()])
    submit = SubmitField('Registrar')

app/__init__.py
from  flask  import Flask
from .public import public_d
# from .admin import admin
from .clients import clients
from .routes import error404
# from .proveedores import proveedores
#from .clients.models import db




def create_app(entorno ):
    app = Flask(__name__)
    # carga de los parámetros de configuracion
    app.config.from_object(entorno)
    
    #login flask
    #login_manager.init_app(app)

    # inicio base de datos
    #db.init_app(app)
    

    

    # Registro los BluePrints de los módulos
    app.register_blueprint(public_d)
    # app.register_blueprint(admin)
    app.register_blueprint(clients)
    app.register_blueprint(error404)
    # app.register_blueprint(proveedores)
    
    #login_manager.login_view = "clients.login"
    #
    # with app.app_context():
    #     db.create_all()
    
    return app

app/admin/__init__.py
# creacion e inicilalizacion de blueprint
from flask import Blueprint

admin = Blueprint('admin', __name__, template_folder='templates', static_folder='static')

#todas las rutas(vistas) del paquete public
from . import routes

app/admin/routes.py
from flask import render_template
from . import  admin

# vistas de dominio público

@admin.route('/admin')
def index():
    return "<p>ona admin - logueo ee ide3ntificacion </p>"

app/clients/__init__.py
# creacion e inicilalizacion de blueprint
from flask import Blueprint


clients = Blueprint('client', __name__, template_folder='templates/clients', static_folder='static')

#todas las rutas(vistas) del paquete clients
from . import routes

app/clients/routes.py
from urllib.parse import urlparse
from flask import redirect, render_template, request, url_for
import flask
from app.clients.forms import LoginClientes
from app.clients.models import Cliente
from . import  clients
from flask_login import LoginManager, logout_user, login_user, login_required


# componente que gestiona los login
#login_manager = LoginManager()

@clients.route('/clients',  methods=["GET", "POST"])
def login():
    form = LoginClientes()
    if form.validate_on_submit():
        email = form.email.data
        password = form.password.data
        print(email, password)
        
        #login_user(Cliente)
        print('LOGUEADOOOOOOOOOOOOOOOOOOOOOOO')
        
        
        next_page = request.args.get('next', None)
        if not next_page or urlparse(next_page).netloc != '':
                next_page = url_for('login_client.client')
                return redirect(next_page)
    return render_template("login.html", form=form)

# @clients.route("/settings")
# @login_required
# def settings():
#     pass

app/proveedores/__init__.py
# creacion e inicilalizacion de blueprint
from flask import Blueprint
#todas las rutas(vistas) del módulo public


proveedores = Blueprint('proveedor', __name__, template_folder='templates/proveedores', static_folder='static')

from . import routes

app/proveedores/routes.py
from flask import render_template
from . import proveedores

# vistas de proveedores

@proveedores.route('/proveedores')
def index():
    return "<p>zona provedor</p>"

app/routes.py
from flask import render_template, Blueprint


error404 = Blueprint('error404', __name__)

#errores NO ENCONTRADO
@error404.app_errorhandler(404)
def pagina_no_encontrada(e):
    return render_template('pag404.html'), 404

app/templates/base_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha3/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- <link rel="stylesheet" href="{{url_for('static', filename = 'main.css')}}"> -->
    <meta content='maximum-scale=1.0, initial-scale=1.0, width=device-width' name='viewport'>
    <title>{% block title %} Gestión de inventario {% endblock %}</title>
</head>
<body>
    {% block menu%}
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{{url_for('public_d.index')}}">App de gestión</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
          
            <li class="nav-item">
              <a class="nav-link " href="{{url_for('client.login')}}"><button type="button" class="btn btn-primary">Acceso Clientes</button></a>
              </li>
              <li class="nav-item">
                <a class="nav-link " href="{{url_for('proveedor.index')}}"><button type="button" class="btn btn-primary">Acceso Proveedores</button></a>
                </li>
          </ul>
        </div>
      </nav>
    {% endblock %}

    {% block contenido %}

    {% endblock %}
    
</body>
</html>

app/templates/pag404.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>pagina 404</h2>
</body>
</html>